"""
Split-Stay Engine — Phase 2

When the ShuffleEngine returns NOT_POSSIBLE (no single room can cover all nights
even with reshuffling), this engine finds a plan that covers every night by
distributing the guest across 2–3 rooms of the same category.

Algorithm: greedy lookahead interval covering
  For each night, stay in the current room if it's free.
  When forced to switch, pick the free room that covers the most
  consecutive future nights (lookahead). Cap at 3 segments (2 handoffs).

Discount tiers:
  1 segment  (no change) →  0 %  (shouldn't happen normally)
  2 segments (1 handoff) →  5 %
  3 segments (2 handoffs) → 10 %
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Optional

from core.models.enums import BlockType, RoomCategory
from services.algorithm.calendar_optimiser import SlotInfo

MAX_SEGMENTS = 3
DISCOUNT_TABLE = {1: 0.0, 2: 5.0, 3: 10.0}


@dataclass
class SplitSegment:
    room_id:    str
    floor:      int
    check_in:   date
    check_out:  date          # exclusive — guest leaves this day
    nights:     int
    base_rate:  float
    discounted_rate: float    # base_rate × (1 - discount_pct/100)


@dataclass
class SplitPlan:
    state:          str       # SPLIT_POSSIBLE | NOT_POSSIBLE
    segments:       list[SplitSegment] = field(default_factory=list)
    stay_group_id:  Optional[str] = None   # generated by controller on confirm
    discount_pct:   float = 0.0
    total_nights:   int   = 0
    total_rate:     float = 0.0            # sum of (nights × discounted_rate) per segment
    message:        str   = ""


class SplitStayEngine:
    def __init__(self, slots: list[SlotInfo], floor_map: dict[str, int]):
        """
        slots     : full scan-window slots for the category (same as ShuffleEngine input)
        floor_map : {room_id: floor_number} — loaded separately since SlotInfo is floor-blind
        """
        self._floor_map = floor_map
        # {room_id: {date: block_type}}
        self._matrix: dict[str, dict[date, BlockType]] = {}
        # {room_id: base_rate}
        self._rates: dict[str, float] = {}

        for s in slots:
            self._matrix.setdefault(s.room_id, {})[s.date] = s.block_type
            self._rates[s.room_id] = s.base_rate

    # ── public entry point ────────────────────────────────────────────────────

    def search(
        self,
        category: RoomCategory,
        check_in: date,
        check_out: date,
    ) -> SplitPlan:
        nights = _date_range(check_in, check_out)
        if not nights:
            return SplitPlan(state="NOT_POSSIBLE", message="Invalid date range.")

        all_rooms = list(self._matrix.keys())
        if not all_rooms:
            return SplitPlan(
                state="NOT_POSSIBLE",
                message=f"No active {category.value} rooms found.",
            )

        # For each night, which rooms are EMPTY?
        free: dict[date, list[str]] = {}
        for night in nights:
            free[night] = [
                r for r in all_rooms
                if self._matrix.get(r, {}).get(night, BlockType.EMPTY) == BlockType.EMPTY
            ]

        # If any night has zero free rooms → split stay physically impossible
        blocked = [n for n in nights if not free[n]]
        if blocked:
            return SplitPlan(
                state="NOT_POSSIBLE",
                message=(
                    f"No {category.value} room is free on "
                    f"{', '.join(str(d) for d in blocked[:3])}"
                    f"{'…' if len(blocked) > 3 else ''}. "
                    "A split stay cannot cover these dates."
                ),
            )

        # Greedy: stay in current room as long as possible; on forced switch pick
        # the room that stays free for the most consecutive future nights.
        segments: list[tuple[str, date, date]] = []  # (room_id, seg_start, seg_end_excl)
        current_room: Optional[str] = None
        seg_start = check_in

        for night in nights:
            if current_room is not None and current_room in free[night]:
                continue  # same room still free — keep going

            if current_room is not None:
                segments.append((current_room, seg_start, night))

            if len(segments) >= MAX_SEGMENTS:
                return SplitPlan(
                    state="NOT_POSSIBLE",
                    message=(
                        f"A {category.value} split stay would require more than "
                        f"{MAX_SEGMENTS} room changes — not offered."
                    ),
                )

            # Pick best room: most consecutive free nights starting tonight
            current_room = max(
                free[night],
                key=lambda r: _consecutive_free(r, night, nights, free),
            )
            seg_start = night

        segments.append((current_room, seg_start, check_out))

        if len(segments) > MAX_SEGMENTS:
            return SplitPlan(
                state="NOT_POSSIBLE",
                message=(
                    f"A {category.value} split stay would require "
                    f"{len(segments)} segments — exceeds the {MAX_SEGMENTS}-segment limit."
                ),
            )

        # A 1-segment plan means a single room covers everything — that's a normal
        # booking, not a split stay. Let the ShuffleEngine handle it instead.
        if len(segments) == 1:
            return SplitPlan(
                state="NOT_POSSIBLE",
                message=(
                    f"A single {category.value} room covers all nights — "
                    "no split stay needed. Use the standard booking flow."
                ),
            )

        discount_pct = DISCOUNT_TABLE.get(len(segments), 0.0)
        total_rate   = 0.0
        built: list[SplitSegment] = []

        for i, (room_id, ci, co) in enumerate(segments):
            n      = (co - ci).days
            rate   = self._rates.get(room_id, 0.0)
            disc_r = round(rate * (1 - discount_pct / 100), 2)
            total_rate += n * disc_r
            built.append(SplitSegment(
                room_id         = room_id,
                floor           = self._floor_map.get(room_id, 0),
                check_in        = ci,
                check_out       = co,
                nights          = n,
                base_rate       = rate,
                discounted_rate = disc_r,
            ))

        n_changes = len(built) - 1
        msg = (
            f"Split stay across {len(built)} rooms "
            f"({'1 room change' if n_changes == 1 else f'{n_changes} room changes'}). "
            f"{int(discount_pct)}% consecutive-stay discount applied. "
            f"Total: ${total_rate:,.0f} for {len(nights)} nights."
        )

        return SplitPlan(
            state        = "SPLIT_POSSIBLE",
            segments     = built,
            discount_pct = discount_pct,
            total_nights = len(nights),
            total_rate   = round(total_rate, 2),
            message      = msg,
        )


# ── helpers ───────────────────────────────────────────────────────────────────

def _date_range(check_in: date, check_out: date) -> list[date]:
    out, cur = [], check_in
    while cur < check_out:
        out.append(cur)
        cur += timedelta(days=1)
    return out


def _consecutive_free(
    room: str,
    from_night: date,
    all_nights: list[date],
    free: dict[date, list[str]],
) -> int:
    """Count how many consecutive nights starting at from_night this room stays free."""
    count = 0
    past_start = False
    for night in all_nights:
        if night < from_night:
            continue
        past_start = True
        if room in free.get(night, []):
            count += 1
        else:
            break
    return count if past_start else 0
